defmodule AdventOfCode2024.Day8Test do
  use ExUnit.Case
  doctest AdventOfCode2024.Day8

  alias AdventOfCode2024.Day8

  describe "run/1" do
    test "counts how many unique locations within the bounds of the map contain an antinode" do
      input =
        """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        """

      assert Day8.run(input) == {:ok, 119}
    end
  end
end
